# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "vite-upload"
client_id = "434128be1633997859b76fd851caca8e"
application_url = "https://manufacturer-fibre-humanities-weekend.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://manufacturer-fibre-humanities-weekend.trycloudflare.com/auth/callback",
  "https://manufacturer-fibre-humanities-weekend.trycloudflare.com/auth/shopify/callback",
  "https://manufacturer-fibre-humanities-weekend.trycloudflare.com/api/auth/callback",
  "https://manufacturer-fibre-humanities-weekend.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "squirrels-and-squirrels.myshopify.com"
