# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "img-upload"
client_id = "3947c525acc29c77d4b9c4307d5c4bcc"
application_url = "https://tunes-spider-kissing-extent.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://tunes-spider-kissing-extent.trycloudflare.com/auth/callback",
  "https://tunes-spider-kissing-extent.trycloudflare.com/auth/shopify/callback",
  "https://tunes-spider-kissing-extent.trycloudflare.com/api/auth/callback",
  "https://tunes-spider-kissing-extent.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "squirrels-and-squirrels.myshopify.com"
